customCommands:
  - key: '<c-l>'
    context: 'files'
    command: 'zsh -c "lumen draft | tee >(pbcopy)"'
    loadingText: 'Generating message...'
    output: popup
  - key: '<c-k>'
    context: 'files'
    command: 'zsh -c "lumen draft -c {{.Form.Context | quote}} | tee >(pbcopy)"'
    loadingText: 'Generating message...'
    prompts:
      - type: 'input'
        title: 'Context'
        key: 'Context'
    output: popup
