customCommands:
  - key: '<c-l>'
    context: 'files'
    command: 'lumen draft | pbcopy; pbpaste'
    loadingText: 'Generating message...'
    output: popup
  - key: '<c-k>'
    context: 'files'
    command: 'lumen draft -c {{.Form.Context | quote}} | pbcopy'
    loadingText: 'Generating message...'
    prompts:
      - type: 'input'
        title: 'Context'
        key: 'Context'
    output: popup
