"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
right_format = "$time"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$python\
$cmd_duration\
$character"""

[line_break]
disabled = true

[directory]
style = "bold green"
truncation_length = 7
truncation_symbol = "…/"
truncate_to_repo = false

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[git_branch]
symbol = " "
format = "|[ $symbol$branch]($style)"
style = "yellow"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed )]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "yellow"

[cmd_duration]
min_time = 10000
format = "|[ $duration ]($style)"
style = "yellow"

[python]
symbol = " "
format = "|[${pyenv_prefix} $symbol(${version} )(($virtualenv) )]($style)"
style = "bright-green"
detect_extensions = []
detect_files = []

[time]
disabled = false
time_format = "%T"
format = '[$time ]($style)'
style = "dimmed yellow"
